name: Build iOS App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-12  # Use macos-12 or macos-11 for x86_64 architecture

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'  # Set the exact version of Flutter

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install

      - name: Build iOS app
        run: flutter build ios --no-codesign
